name: nba
channels:
  - conda-forge
  - defaults
dependencies:
  - lightgbm
  - matplotlib
  - numpy
  - optuna
  - pandas
  - plotly
  - pyarrow
  - python=3.10
  - pytorch
  - pyyaml
  - scikit-learn
  - scipy
  - seaborn
  - torchaudio
  - torchvision
  - streamlit
  - pip
  - pip:
    - nba-api==1.10.1
prefix: /opt/anaconda3/envs/nba
