# Directories
raw_data_dir: './data/raw'
clean_data_dir: './data/clean'
model_src_dir: './src/models'
model_save_dir: './models'

# File names (to be updated)
raw_file_name: 'raw.csv'
db_name: 'my_database.db'